### ISSUE TITLE
A Few Continuous Errors

### ISSUE THREAD

**Issue by ThatGuy25** [0ADMods/ponies-ascendant#45]
Heya! Just making a message here to help things get ironed out. It seems that the only issues are the model bones to animations ratio, and the errors had when the characters try using props. I'm new to the game, so sorry if my language isn't helpful. Attached is a screenshot of my errors. (On personal note, I don't mind the errors in the game, but they just keep popping on my screen in console)
Best of wishes working on this, the mod and game is really fun! <3
![image](https://user-images.githubusercontent.com/113882347/190960613-90a42361-ecb9-43e7-9524-16732a95c412.png)

**Comment by StanleySweet** [comment]
Hey, just to make sure, which version are you using? :) 
Any help to get it up and ready for the new release is welcome:

**Comment by ThatGuy25** [comment]
I was using the newest version, 0.0.25b, at the time. Though now I also see there's a 0.0.26 alpha release for the game.
